// NOTE:
// This app relies on runtime DB access for authenticated pages (dashboard, reports, etc).
// During Docker image build (`next build`), static prerendering can accidentally execute
// DB calls and fail with ECONNREFUSED. For on-prem production reliability, we force
// dynamic rendering at runtime (no build-time prerender).
export const dynamic = "force-dynamic";
export const revalidate = 0;
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
